# NumPy — Complete Reference Notebook

**What is NumPy?** NumPy (Numerical Python) is the foundational library for numerical computing in Python. Almost every ML library — pandas, scikit-learn, matplotlib — is built on top of it.

**Why learn it deeply?** When you understand NumPy well, you can debug shape errors, write vectorized code that runs 100x faster than loops, and understand what ML frameworks are doing under the hood.

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/YOUR_USERNAME/ml-mastery/blob/main/01_libraries/numpy.ipynb)

---

## Table of Contents
1. [Import & Setup](#1-import--setup)
2. [Creating Arrays](#2-creating-arrays)
3. [Array Attributes](#3-array-attributes)
4. [Indexing & Slicing](#4-indexing--slicing)
5. [Reshaping & Stacking](#5-reshaping--stacking)
6. [Math Operations](#6-math-operations)
7. [Broadcasting](#7-broadcasting)
8. [Boolean Indexing & Filtering](#8-boolean-indexing--filtering)
9. [Linear Algebra](#9-linear-algebra)
10. [Random Module](#10-random-module)
11. [Common Gotchas](#11-common-gotchas)
12. [Exercises](#12-exercises)


## 1. Import & Setup

In [38]:
import numpy as np

print("NumPy version:", np.__version__)


NumPy version: 2.0.2


## 2. Creating Arrays

These are the most common ways to create arrays. Pay attention to the **dtype** — it matters for memory and precision.

In [39]:
# From a Python list
a = np.array([1, 2, 3, 4, 5])
print("1D array:", a)
print("dtype:", a.dtype)          # int64 by default

# 2D array (matrix) — list of lists
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print("\n2D array:\n", b)
print("shape:", b.shape)          # (rows, cols)


1D array: [1 2 3 4 5]
dtype: int64

2D array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)


In [40]:
# Specify dtype explicitly
c = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print("float32 array:", c)
print("dtype:", c.dtype)

# Cast later
d = np.array([1, 2, 3]).astype(np.float64)
print("cast to float64:", d)


float32 array: [1. 2. 3.]
dtype: float32
cast to float64: [1. 2. 3.]


In [41]:
# Built-in constructors — use these constantly in ML
print("zeros (3x4):\n",       np.zeros((3, 4)))
print("\nones (2x3):\n",      np.ones((2, 3)))
print("\nfull (2x2, val=7):\n", np.full((2, 2), 7))
print("\nidentity (3x3):\n", np.eye(3))


zeros (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ones (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]

full (2x2, val=7):
 [[7 7]
 [7 7]]

identity (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
# Sequences
print("arange(0, 10, 2):", np.arange(0, 10, 2))       # like range() but returns array
print("linspace(0,1,6):", np.linspace(0, 1, 6))       # evenly spaced including endpoint
print("logspace(0,3,4):", np.logspace(0, 3, 4))       # evenly spaced on log scale


arange(0, 10, 2): [0 2 4 6 8]
linspace(0,1,6): [0.  0.2 0.4 0.6 0.8 1. ]
logspace(0,3,4): [   1.   10.  100. 1000.]


## 3. Array Attributes

Before doing any operation, always check these.

In [43]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=np.float32)

print("shape:    ", a.shape)       # (3, 3)
print("ndim:     ", a.ndim)        # number of dimensions
print("size:     ", a.size)        # total number of elements
print("dtype:    ", a.dtype)       # data type
print("itemsize: ", a.itemsize)    # bytes per element
print("nbytes:   ", a.nbytes)      # total bytes in memory


shape:     (3, 3)
ndim:      2
size:      9
dtype:     float32
itemsize:  4
nbytes:    36


## 4. Indexing & Slicing

NumPy slicing returns **views**, not copies. This is a common source of bugs — see the Gotchas section.

In [44]:
a = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

# Single element
print("a[0, 2]  =", a[0, 2])      # row 0, col 2  → 30
print("a[2, -1] =", a[2, -1])     # row 2, last col → 90

# Row and column selection
print("Row 1:      ", a[1])           # [40 50 60]
print("Col 0:      ", a[:, 0])        # [10 40 70]
print("Last col:   ", a[:, -1])       # [30 60 90]


a[0, 2]  = 30
a[2, -1] = 90
Row 1:       [40 50 60]
Col 0:       [10 40 70]
Last col:    [30 60 90]


In [45]:
# Slicing [start:stop:step]  — stop is EXCLUSIVE
print("Rows 0-1:        \n", a[0:2, :])
print("Rows 0-1, col 1-2:\n", a[0:2, 1:3])
print("Every other row: \n", a[::2, :])
print("Reversed rows:   \n", a[::-1, :])


Rows 0-1:        
 [[10 20 30]
 [40 50 60]]
Rows 0-1, col 1-2:
 [[20 30]
 [50 60]]
Every other row: 
 [[10 20 30]
 [70 80 90]]
Reversed rows:   
 [[70 80 90]
 [40 50 60]
 [10 20 30]]


In [46]:
# Fancy indexing — selects elements at given indices
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print("Fancy index:", arr[indices])    # [10 30 50]

# Pick specific rows from a matrix
mat = np.array([[1,2],[3,4],[5,6],[7,8]])
print("Rows 0 and 2:\n", mat[[0, 2]])


Fancy index: [10 30 50]
Rows 0 and 2:
 [[1 2]
 [5 6]]


## 5. Reshaping & Stacking

Shape manipulation is something you will do constantly in ML — when feeding data into models, combining batches, etc.

In [47]:
a = np.arange(12)
print("Original:", a)

# reshape — total elements must stay the same
b = a.reshape(3, 4)
print("\nreshaped (3,4):\n", b)

c = a.reshape(2, 2, 3)
print("\nreshaped (2,2,3):\n", c)

# -1 means 'figure this dimension out automatically'
d = a.reshape(4, -1)
print("\nreshaped (4,-1):\n", d)    # -1 → 3


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshaped (3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshaped (2,2,3):
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

reshaped (4,-1):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [48]:
# flatten vs ravel
a = np.array([[1, 2], [3, 4]])

flat  = a.flatten()   # always returns a COPY
rav   = a.ravel()     # returns a VIEW when possible (faster)

flat[0] = 999
print("Original after modifying flatten:", a[0,0])   # 1 — not affected

rav[0] = 999
print("Original after modifying ravel:",  a[0,0])    # 999 — affected!


Original after modifying flatten: 1
Original after modifying ravel: 999


In [49]:
# Adding/removing dimensions
a = np.array([1, 2, 3])      # shape (3,)
print("Original shape:", a.shape)

b = a[np.newaxis, :]         # shape (1, 3) — row vector
c = a[:, np.newaxis]         # shape (3, 1) — column vector
d = np.expand_dims(a, axis=0)  # same as newaxis

print("newaxis row:   ", b.shape)
print("newaxis col:   ", c.shape)
print("squeeze:",  np.squeeze(b).shape)   # removes dim-1 axes → (3,)


Original shape: (3,)
newaxis row:    (1, 3)
newaxis col:    (3, 1)
squeeze: (3,)


In [50]:
# Stacking arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("vstack (vertical / row-wise):\n",    np.vstack([a, b]))
print("\nhstack (horizontal / col-wise):\n", np.hstack([a, b]))
print("\nconcatenate axis=0:\n",             np.concatenate([a, b], axis=0))
print("\nconcatenate axis=1:\n",             np.concatenate([a, b], axis=1))


vstack (vertical / row-wise):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack (horizontal / col-wise):
 [[1 2 5 6]
 [3 4 7 8]]

concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


## 6. Math Operations

NumPy operations are **element-wise by default**. Matrix multiplication is a separate operation.

In [51]:
a = np.array([[1, 2], [3, 4]], dtype=float)
b = np.array([[5, 6], [7, 8]], dtype=float)

print("Element-wise +:\n", a + b)
print("Element-wise *:\n", a * b)   # NOT matrix multiplication
print("Element-wise **2:\n", a ** 2)
print("\nMatrix multiplication (a @ b):\n", a @ b)
print("Same with np.dot:\n", np.dot(a, b))


Element-wise +:
 [[ 6.  8.]
 [10. 12.]]
Element-wise *:
 [[ 5. 12.]
 [21. 32.]]
Element-wise **2:
 [[ 1.  4.]
 [ 9. 16.]]

Matrix multiplication (a @ b):
 [[19. 22.]
 [43. 50.]]
Same with np.dot:
 [[19. 22.]
 [43. 50.]]


In [52]:
# Aggregation — axis matters
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Total sum:       ", np.sum(a))
print("Sum along axis=0 (per column):", np.sum(a, axis=0))   # [5 7 9]
print("Sum along axis=1 (per row):   ", np.sum(a, axis=1))   # [6 15]
print()
print("mean axis=0:", np.mean(a, axis=0))
print("std  axis=1:", np.std(a, axis=1))
print("max  axis=0:", np.max(a, axis=0))
print("argmax (flat):", np.argmax(a))         # index in flattened array
print("argmax axis=1:", np.argmax(a, axis=1)) # index of max per row


Total sum:        21
Sum along axis=0 (per column): [5 7 9]
Sum along axis=1 (per row):    [ 6 15]

mean axis=0: [2.5 3.5 4.5]
std  axis=1: [0.81649658 0.81649658]
max  axis=0: [4 5 6]
argmax (flat): 5
argmax axis=1: [2 2]


In [53]:
# Universal functions (ufuncs) — applied element-wise
x = np.array([0, np.pi/2, np.pi])

print("sin:", np.sin(x))
print("cos:", np.cos(x))
print("exp:", np.exp([0, 1, 2]))
print("log:", np.log([1, np.e, np.e**2]))
print("sqrt:", np.sqrt([1, 4, 9, 16]))
print("abs:", np.abs([-3, -1, 0, 2]))


sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
exp: [1.         2.71828183 7.3890561 ]
log: [0. 1. 2.]
sqrt: [1. 2. 3. 4.]
abs: [3 1 0 2]


## 7. Broadcasting

Broadcasting is how NumPy handles operations between arrays of different shapes.

**The rule:** Two dimensions are compatible if they are **equal**, or one of them is **1**.
NumPy pads the shapes from the right to compare them.

```
Shape (3, 4) + shape (4,)  → (4,) becomes (1,4) → broadcasts to (3,4)  ✓
Shape (3, 4) + shape (3,)  → (3,) becomes (1,3) → can't broadcast to (3,4)  ✗
Shape (3, 1) + shape (1,4) → broadcasts to (3,4)  ✓
```


In [54]:
# Example 1: add scalar to matrix
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix + scalar:\n", a + 10)    # 10 broadcasts to every element


Matrix + scalar:
 [[11 12 13]
 [14 15 16]]


In [55]:
# Example 2: add 1D array to 2D array (row-wise)
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])            # shape (3,) → treated as (1,3)

print("a shape:", a.shape)
print("b shape:", b.shape)
print("a + b:\n", a + b)             # adds b to each row


a shape: (2, 3)
b shape: (3,)
a + b:
 [[11 22 33]
 [14 25 36]]


In [56]:
# Example 3: column vector + row vector → full matrix
col = np.array([[0], [10], [20]])     # shape (3,1)
row = np.array([1, 2, 3])            # shape (3,) → (1,3)

print("col:\n", col)
print("row:", row)
print("col + row:\n", col + row)    # broadcasts to (3,3)


col:
 [[ 0]
 [10]
 [20]]
row: [1 2 3]
col + row:
 [[ 1  2  3]
 [11 12 13]
 [21 22 23]]


In [57]:
# Practical ML use: standardize each feature (column)
X = np.array([[1.0, 200.0],
              [2.0, 150.0],
              [3.0, 300.0]])

mean = X.mean(axis=0)   # shape (2,)
std  = X.std(axis=0)    # shape (2,)

X_scaled = (X - mean) / std   # broadcasting: (3,2) - (2,) / (2,) → (3,2)
print("Scaled X:\n", X_scaled.round(3))
print("Means after scaling:", X_scaled.mean(axis=0).round(10))  # ~0
print("Stds  after scaling:", X_scaled.std(axis=0).round(10))   # ~1


Scaled X:
 [[-1.225 -0.267]
 [ 0.    -1.069]
 [ 1.225  1.336]]
Means after scaling: [0. 0.]
Stds  after scaling: [1. 1.]


## 8. Boolean Indexing & Filtering

In [58]:
a = np.array([10, 25, 5, 40, 15, 30])

# Boolean mask
mask = a > 20
print("mask:", mask)              # [False  True False  True False  True]
print("a[mask]:", a[mask])        # [25 40 30]

# Inline
print("values > 20:", a[a > 20])

# Combined conditions
print("10 < a < 30:", a[(a > 10) & (a < 30)])   # use & not 'and'
print("a < 10 or a > 30:", a[(a < 10) | (a > 30)])


mask: [False  True False  True False  True]
a[mask]: [25 40 30]
values > 20: [25 40 30]
10 < a < 30: [25 15]
a < 10 or a > 30: [ 5 40]


In [59]:
# np.where — vectorized if-else
a = np.array([1, -2, 3, -4, 5])

result = np.where(a > 0, a, 0)   # if a>0 keep value, else replace with 0
print("ReLU-like:", result)       # [1 0 3 0 5]

# np.where with just condition → returns indices
idx = np.where(a > 0)
print("Indices where a>0:", idx)  # (array([0, 2, 4]),)
print("Values at those indices:", a[idx])


ReLU-like: [1 0 3 0 5]
Indices where a>0: (array([0, 2, 4]),)
Values at those indices: [1 3 5]


## 9. Linear Algebra

This is the foundation of almost every ML algorithm. Normal equations, PCA, SVD — all use these.

In [60]:
A = np.array([[2, 1],
              [5, 3]], dtype=float)

print("Determinant:    ", np.linalg.det(A))
print("Inverse:\n",      np.linalg.inv(A))
print("Verify A @ inv(A) ≈ I:\n", (A @ np.linalg.inv(A)).round(10))


Determinant:     1.0000000000000009
Inverse:
 [[ 3. -1.]
 [-5.  2.]]
Verify A @ inv(A) ≈ I:
 [[ 1.  0.]
 [-0.  1.]]


In [61]:
# Solve linear system Ax = b
A = np.array([[2, 1], [5, 3]], dtype=float)
b = np.array([8, 21], dtype=float)

x = np.linalg.solve(A, b)
print("Solution x:", x)
print("Verify A @ x == b:", np.allclose(A @ x, b))


Solution x: [3. 2.]
Verify A @ x == b: True


In [62]:
# Eigenvalues and eigenvectors — used in PCA
A = np.array([[3, 1],
              [1, 3]], dtype=float)

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors (columns):\n", eigenvectors)


Eigenvalues: [4. 2.]
Eigenvectors (columns):
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [63]:
# Norms — used in regularization and distance calculations
v = np.array([3.0, 4.0])

print("L1 norm (sum of abs):", np.linalg.norm(v, ord=1))   # 7.0
print("L2 norm (Euclidean): ", np.linalg.norm(v))          # 5.0
print("L∞ norm (max abs):   ", np.linalg.norm(v, ord=np.inf))  # 4.0


L1 norm (sum of abs): 7.0
L2 norm (Euclidean):  5.0
L∞ norm (max abs):    4.0


## 10. Random Module

Always set a seed for reproducibility.

In [64]:
rng = np.random.default_rng(seed=42)   # recommended modern way

print("Uniform [0,1):    ", rng.random(5))
print("Standard normal:  ", rng.standard_normal(5))
print("Integers [0,10):  ", rng.integers(0, 10, size=5))
print("Normal(mean,std): ", rng.normal(loc=5, scale=2, size=5))

# Shuffle and choice
arr = np.arange(10)
rng.shuffle(arr)
print("Shuffled:         ", arr)
print("Random choice:    ", rng.choice(arr, size=3, replace=False))


Uniform [0,1):     [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
Standard normal:   [-1.30217951  0.1278404  -0.31624259 -0.01680116 -0.85304393]
Integers [0,10):   [5 3 1 9 7]
Normal(mean,std):  [7.25448241 5.93501868 3.28141507 5.73750157 3.0822348 ]
Shuffled:          [6 9 2 7 3 5 8 4 0 1]
Random choice:     [4 3 0]


## 11. Common Gotchas

These cause silent bugs that are very hard to track down.

In [65]:
# GOTCHA 1: Slices return views, not copies
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]       # b is a VIEW of a
b[0] = 999

print("a after modifying b:", a)   # [  1 999   3   4   5] — a changed!

# Fix: use .copy()
b = a[1:4].copy()
b[0] = 0
print("a after modifying copy:", a)   # unchanged


a after modifying b: [  1 999   3   4   5]
a after modifying copy: [  1 999   3   4   5]


In [66]:
# GOTCHA 2: Integer division in array creation
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("int / int:", a / b)          # [0.25 0.4  0.5 ] — OK in Python 3
print("int dtype:", (a / b).dtype)  # float64 — Python 3 auto-promotes

# But watch out with integer arrays and some operations
c = np.array([1, 2, 3], dtype=np.int32)
print("\nint32 array:", c)
print("int32 / 2:", c / 2)          # float64 — safe
print("int32 // 2:", c // 2)        # int32 — floor division stays int


int / int: [0.25 0.4  0.5 ]
int dtype: float64

int32 array: [1 2 3]
int32 / 2: [0.5 1.  1.5]
int32 // 2: [0 1 1]


In [67]:
# GOTCHA 3: Shape (n,) vs shape (n,1) — they behave differently
a = np.array([1, 2, 3])       # shape (3,)  — 1D
b = np.array([[1], [2], [3]]) # shape (3,1) — 2D column vector

print("1D shape:", a.shape)
print("2D shape:", b.shape)

# Dot product behaves differently
c = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])  # (3,3)
print("\nc @ a shape:", (c @ a).shape)   # (3,) 
print("c @ b shape:", (c @ b).shape)   # (3,1)

# Fix: reshape when needed
a_col = a.reshape(-1, 1)   # or a[:, np.newaxis]
print("Reshaped to col:", a_col.shape)


1D shape: (3,)
2D shape: (3, 1)

c @ a shape: (3,)
c @ b shape: (3, 1)
Reshaped to col: (3, 1)


In [68]:
# GOTCHA 4: np.sum vs .sum() — axis confusion
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print("No axis — sum everything:", a.sum())               # 21
print("axis=0 — sum down rows (per col):", a.sum(axis=0)) # [5 7 9]
print("axis=1 — sum across cols (per row):", a.sum(axis=1)) # [6 15]

# Memory trick: axis=0 collapses the first dimension (rows disappear)
#               axis=1 collapses the second dimension (cols disappear)


No axis — sum everything: 21
axis=0 — sum down rows (per col): [5 7 9]
axis=1 — sum across cols (per row): [ 6 15]


## 12. Exercises

Try these before looking at the solutions.

**Exercise 1:** Create a 5x5 matrix with values 1–25, then extract the 3x3 submatrix from the center.

In [69]:
# Your code here


In [70]:
# Solution
mat = np.arange(1, 26).reshape(5, 5)
print("Full matrix:\n", mat)
center = mat[1:4, 1:4]
print("\nCenter 3x3:\n", center)


Full matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Center 3x3:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


**Exercise 2:** Given an array of exam scores, normalize them to [0, 1] range using min-max scaling without using sklearn.

In [71]:
# Your code here
scores = np.array([45, 78, 23, 95, 67, 88, 12, 100])


In [72]:
# Solution
scores = np.array([45, 78, 23, 95, 67, 88, 12, 100])
normalized = (scores - scores.min()) / (scores.max() - scores.min())
print("Normalized:", normalized.round(3))
print("Min:", normalized.min(), "Max:", normalized.max())  # should be 0.0 and 1.0


Normalized: [0.375 0.75  0.125 0.943 0.625 0.864 0.    1.   ]
Min: 0.0 Max: 1.0


**Exercise 3:** Using only NumPy (no sklearn), compute the Euclidean distance between every pair of rows in this matrix.

In [73]:
# Your code here
X = np.array([[1.0, 2.0],
              [4.0, 6.0],
              [7.0, 8.0]])


In [74]:
# Solution — broadcasting approach
X = np.array([[1.0, 2.0],
              [4.0, 6.0],
              [7.0, 8.0]])

# X[:, np.newaxis] shape: (3,1,2) — X[np.newaxis,:] shape: (1,3,2)
# diff shape: (3,3,2) — each [i,j,:] is X[i] - X[j]
diff = X[:, np.newaxis, :] - X[np.newaxis, :, :]
dist = np.sqrt((diff ** 2).sum(axis=2))
print("Distance matrix:\n", dist.round(3))


Distance matrix:
 [[0.    5.    8.485]
 [5.    0.    3.606]
 [8.485 3.606 0.   ]]


---

## 👨‍💻 Author

**Himanshu Kumar**

- 🌐 GitHub: [@himanshu231204](https://github.com/himanshu231204)
- 💼 LinkedIn: [himanshu231204](https://www.linkedin.com/in/himanshu231204)
- 🐦 Twitter/X: [@himanshu231204](https://twitter.com/himanshu231204)
- 📧 Email: himanshu231204@gmail.com
